<?php

//USER WANTS TO EDIT TITLE
//USER WANTS TO EDIT TEXT
//USER WANTS TO EDIT TAGS
//USER WANTS TO PUBLISH A POST THAT HAS NOT BEEN PUBLISHED
/*
 * NEEDED VARIABLES:
 * 1. THE ID OF THE BLOG POST
 */
$query = "UPDATE `blogs` SET `published_timestamp`= NOW() WHERE `id` = 2";
//USER WANTS TO CHANGE FROM PRIVATE TO PUBLIC
